# Site settings
title: Karishma Changlani
header-img: img/home-bg.jpg
email: karishmachanglani@gmail.com
description: "Welcome! My name is Karishma Changlani and this my website."
baseurl: ""
url: "http://localhost:4000"
twitter_username: Doodler0305
github_username:  KarishmaChanglani
facebook_username: pages/Digitially-Artitstic/437100696439522
gallery_link: "http://doodler0305.deviantart.com/gallery/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#Defaults
defaults:
-
    scope:
        path: ""
        type: "posts"
    values: 
        layout: "post"
        author: "Karishma Changlani"
        